[package]
name = "source-wand-replication"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }

source-wand-common = { path = "../common" }
