[package]
name = "source-wand-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
lxd = "0.1.9"
readonly = "0.2.13"
regex = "1.11.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_yaml = "0.9.34"
